#!/usr/bin/env python3
"""Startup digest — render the most recent day's notes to a markdown file.

Behaviour (per the ingestion brief): find the calendar date (UTC) of the last
note entered, fetch every note from that date, and write them to a markdown doc
under recent/ — overwritten on each run. scripts/up.sh calls this after the
schema is applied, so the doc refreshes whenever the database comes up.

Query design (validated against the live server):
  * `max(created_at)` is read plainly and sliced to YYYY-MM-DD in Python —
    chaining `.format()` onto `max()` proved unreliable.
  * the day's notes are selected with a `date()` range so the created_at index
    is used: created_at >= date('<day> 00:00:00') AND < date('<next> 00:00:00').
"""
import os
import re
from datetime import date, timedelta

import notelib

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "recent")
OUT_FILE = os.path.join(OUT_DIR, "recent-notes.md")
DAY_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def latest_day(db):
    """UTC calendar date (YYYY-MM-DD) of the most recent note, or None if empty."""
    mx = notelib.first_row(db.query("SELECT max(created_at) AS mx FROM Note")).get("mx")
    if not mx:
        return None
    day = str(mx)[:10]
    if not DAY_RE.match(day):
        raise SystemExit(f"[recent-notes] unexpected created_at format from DB: {mx!r}")
    return day


def notes_on(db, day):
    nxt = (date.fromisoformat(day) + timedelta(days=1)).isoformat()
    # `day`/`nxt` are validated YYYY-MM-DD derived from the DB, so literal
    # interpolation into date(...) is safe (no user input, proven form).
    sql = (
        "SELECT id, title, body, created_at, author, source_ref, status FROM Note "
        f"WHERE created_at >= date('{day} 00:00:00') "
        f"AND created_at < date('{nxt} 00:00:00') ORDER BY id")
    return notelib.rows(db.query(sql))


def render(day, notes):
    lines = [
        f"# Recent notes — {day}",
        "",
        f"_The {len(notes)} note(s) entered on {day} (UTC), the most recent day in the "
        "corpus. Generated by `scripts/recent-notes.sh`; overwritten on next startup._",
        "",
    ]
    for n in notes:
        title = n.get("title") or "(untitled)"
        lines.append(f"## {title}")
        meta = [f"`{n.get('id')}`", n.get("author") or notelib.DEFAULT_AUTHOR]
        if n.get("status"):
            meta.append(n["status"])
        lines.append("")
        lines.append(" · ".join(meta))
        lines.append("")
        lines.append((n.get("body") or "").strip())
        lines.append("")
        if n.get("source_ref"):
            lines.append(f"_Source: {n['source_ref']}_")
            lines.append("")
        lines.append("---")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_empty():
    return ("# Recent notes\n\n_No notes in the corpus yet. Add one with "
            "`scripts/add-note.sh` or by dropping a file in `staging/`._\n")


def main():
    db = notelib.Arcade()
    os.makedirs(OUT_DIR, exist_ok=True)
    day = latest_day(db)
    if day is None:
        with open(OUT_FILE, "w", encoding="utf-8") as fh:
            fh.write(render_empty())
        print(f"[recent-notes] corpus empty — wrote placeholder to {OUT_FILE}")
        return
    notes = notes_on(db, day)
    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        fh.write(render(day, notes))
    print(f"[recent-notes] wrote {len(notes)} note(s) from {day} to {OUT_FILE}")


if __name__ == "__main__":
    main()
