#!/usr/bin/env python3
"""resurface — weekly serendipitous re-encounter (spec §8.1 move 6, §12.6).

Surfaces orphan / under-linked and inhibited notes plus an 'on this day' anniversary, so
nothing is forgotten (nothing truly dies, §6). Renders `recent/resurface.md` and logs
Op(RESURFACE). Read-only over the corpus. Run through the wrapper (scripts/resurface.sh);
meant to run weekly.
"""
import argparse
import json
import os
import sys

import notelib

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "recent")
OUT_FILE = os.path.join(OUT_DIR, "resurface.md")


def render(m6):
    L = [f"# Resurfacing — {notelib.format_id(notelib.now_utc())}", "",
         "_Generated by `scripts/resurface.sh`; overwritten on each run. Orphan, inhibited, and "
         "anniversary notes re-encountered so nothing truly dies (spec §6, §8.1 move 6)._", ""]
    for label, bucket, hint in (
            ("Orphans — no ratified link yet", "orphans", "consider linking (provoke.sh --seed)"),
            ("Inhibited — corrected, still re-encounterable", "inhibited",
             "what changed, and why?"),
            ("On this day", "on_this_day", "re-encounter from a past cycle")):
        L += [f"## {label}", f"_{hint}_", ""]
        L += ([f"- `{c['id']}` · {c.get('title') or '(untitled)'}  \n  {c.get('snippet', '')}"
               for c in m6[bucket]] or ["_none_"])
        L += [""]
    return "\n".join(L).rstrip() + "\n"


def main():
    p = argparse.ArgumentParser(prog="resurface",
                                description="Weekly re-encounter of orphan/inhibited notes (§8.1).")
    p.add_argument("-k", "--limit", type=int, default=8, help="notes per bucket (default 8)")
    p.add_argument("--json", action="store_true")
    args = p.parse_args()

    db = notelib.Arcade()
    try:
        m6 = notelib.move6_candidates(db, k=args.limit)
        os.makedirs(OUT_DIR, exist_ok=True)
        with open(OUT_FILE, "w", encoding="utf-8") as fh:
            fh.write(render(m6))
        op_id = notelib.unique_id(db, notelib.format_id(notelib.now_utc()), "Op")
        notelib.insert_op(db, op_id, "RESURFACE",
                          {"orphans": len(m6["orphans"]), "inhibited": len(m6["inhibited"]),
                           "on_this_day": len(m6["on_this_day"])})
    except notelib.ArcadeError as e:
        sys.exit(f"[resurface] failed: {e}\n  SQL: {e.sql}")

    if args.json:
        summary = {k: len(v) for k, v in m6.items()}
        summary["out"] = OUT_FILE
        print(json.dumps(summary, indent=2))
    else:
        print(f"[resurface] wrote {OUT_FILE} · {len(m6['orphans'])} orphan(s), "
              f"{len(m6['inhibited'])} inhibited, {len(m6['on_this_day'])} on-this-day")


if __name__ == "__main__":
    main()
